# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
# Same pandoc version as RStudio (as of Nov 2020)
pandoc_version: 2.7.3

# Install the Ruby gem html-proofer
before_install:
  - gem install html-proofer
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speed up html-proofer install

script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
- htmlproofer --empty-alt-ignore _book

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  local_dir: _book
  on:
    branch: master
