# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
name: site

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GHPAGES_DEPLOY_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup version-stable R 3.6.3
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
        env:
          CRAN: https://mran.microsoft.com/snapshot/2020-04-12
      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@master
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Build site
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::gitbook')
        shell: Rscript {0}

      - name: Upload built site artifact
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: _book

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: _book
